apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-trainee.fullname.nginx" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-trainee.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx-trainee.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nginx-trainee.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "nginx-trainee.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}   
          volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-config-volume
            mountPath: /etc/nginx/sites-enabled/default
            subPath: default.conf
          #- name: nginx-auth
          #  mountPath: /etc/nginx/auth
          #  subPath: yc-key
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: apache-php
          image: beigetamarah/apache2-trainee5:latest
          ports:
            - containerPort: 8080
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:latest
          args:
            - --nginx.scrape-uri=http://127.0.0.1:8888/stub_status
          ports:
            - containerPort: {{ .Values.metrics.port }}
              name: metrics
      
      volumes:
      #- name: nginx-auth
      #  secret:
      #    secretName: {{ include "nginx-trainee.fullname.nginx" . }}
      - name: nginx-config-volume
        configMap:
          name: {{ include "nginx-trainee.fullname.nginx" . }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
